services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
    networks:
      - app-network

  app:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:root123@mongodb:27017/cloud-grafile?authSource=admin
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "4000:4000"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
